[package]
name = "conseqa"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_yaml = { package = "serde_yaml_ng", version = "0.10" }
serde_json = "1"

[[bin]]
name = "conseqa"
path = "src/main.rs"

[[bin]]
name = "conseqa-viz"
path = "src/bin/viz/main.rs"
